[package]
name = "static-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
static-crypto = { path = "../static-crypto" }
static-sphinx = { path = "../static-sphinx" }
static-storage = { path = "../static-storage" }
blake3.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "macros", "rt", "sync", "time"] }
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rand.workspace = true
tracing.workspace = true
ed25519-dalek.workspace = true
futures = "0.3"
async-trait.workspace = true
