[package]
name = "static-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
static-crypto = { path = "../static-crypto" }
static-sphinx = { path = "../static-sphinx" }
blake3.workspace = true
tokio.workspace = true
bytes.workspace = true
serde.workspace = true
thiserror.workspace = true
rand.workspace = true
tracing.workspace = true
